### ISSUE TITLE
Crawler dose not work

### ISSUE THREAD

**Issue by ArchieGu** [mrthlinh/FIFA-World-Cup-Prediction#1]
Hi, 
I want to know if when I use the crawler.py, it gave me the error:

`Traceback (most recent call last):
  File "crawler.py", line 98, in <module>
    version_id = int(sys.argv[1]) - 5
IndexError: list index out of range`

How can I fix this??
Thank you.

**Comment by mrthlinh** [comment]
The command:
```
python crawler <version of FIFA> <start page>
```
The reason I add <start page> because when running, the website may terminate your connection.
For example: here is how you can crawl FIFA 11 player start from page 1 or page 3 of the website fifaindex
```
python crawler 11 1
python crawler 11 3
```
When the connection is terminated you may want to start again but with new starting page.

**Comment by ArchieGu** [comment]
@mrthlinh 
Great! Thanks for your reply.
This is such a wonderful program!!
